var config = [

/****************************************** 		level 1 ----------- JAVA 		******************************************/
{level:"1", theme: "JAVA", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "JAVA", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "JAVA", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "JAVA", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "JAVA", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "JAVA", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "JAVA", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- JAVA 		******************************************/
{level:"2", theme: "JAVA", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "JAVA", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "JAVA", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "JAVA", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "JAVA", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "JAVA", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "JAVA", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- JAVA 		******************************************/
{level:"3", theme: "JAVA", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "JAVA", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "JAVA", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "JAVA", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "JAVA", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "JAVA", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "JAVA", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- JAVA 		******************************************/
{level:"4", theme: "JAVA", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "JAVA", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "JAVA", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "JAVA", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "JAVA", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "JAVA", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "JAVA", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- JAVA 		******************************************/
{level:"5", theme: "JAVA", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "JAVA", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "JAVA", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "JAVA", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "JAVA", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "JAVA", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "JAVA", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},

/****************************************** 		level 1 ----------- Java-Script 		******************************************/
{level:"1", theme: "Java-Script", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "Java-Script", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "Java-Script", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "Java-Script", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "Java-Script", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "Java-Script", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "Java-Script", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- Java-Script 		******************************************/
{level:"2", theme: "Java-Script", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "Java-Script", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "Java-Script", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "Java-Script", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "Java-Script", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "Java-Script", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "Java-Script", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- Java-Script 		******************************************/
{level:"3", theme: "Java-Script", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "Java-Script", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "Java-Script", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "Java-Script", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "Java-Script", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "Java-Script", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "Java-Script", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- Java-Script 		******************************************/
{level:"4", theme: "Java-Script", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "Java-Script", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "Java-Script", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "Java-Script", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "Java-Script", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "Java-Script", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "Java-Script", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- Java-Script 		******************************************/
{level:"5", theme: "Java-Script", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "Java-Script", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "Java-Script", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "Java-Script", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "Java-Script", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "Java-Script", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "Java-Script", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},


/****************************************** 		level 1 ----------- Python 		******************************************/
{level:"1", theme: "Python", question: "Who developed Python Programming Language?", answers: ["Wick van Rossum", "Guido van Rossum", "Rasmus Lerdorf", "All of the mentioned"], correct: 2},
{level:"1", theme: "Python", question: "All keywords in Python are in _________", answers: ["Capitalized", "LOWER CASE", "UPPER CASE", "None of the mentioned."], correct: 3},
{level:"1", theme: "Python", question: "Is Python case sensitive when dealing with identifiers?", answers: ["yes", "no", "machine dependent", "none of the mentioned"], correct: 2},
{level:"1", theme: "Python", question: "EXTENSION OF PYTHON", answers: [".python", ".px", ".py", ".p"], correct: 3},
/****************************************** 		level 2 ----------- Python 		******************************************/
{level:"2", theme: "Python", question: "Is Python code compiled or interpreted?", answers: ["ython code is both compiled and interpreted", " Python code is neither compiled nor interpreted", "Python code is only compiled", " Python code is only interpreted"], correct: 1},
{level:"2", theme: "Python", question: "What will be the value of the following Python expression? 4 + 3 % 5", answers: ["7", "8", "2", "1"], correct: 1},
{level:"2", theme: "Python", question: " Which of the following is used to define a block of code in Python language?", answers: [" Indentation.", "Key", "Brackets", "All of the mentioned"], correct: 1},
{level:"2", theme: "Python", question: "Which keyword is used for function in Python language?", answers: ["Function", "Def", "Fun", "Define"], correct: 2},
/****************************************** 		level 3 ----------- Python 		******************************************/
{level:"3", theme: "Python", question: "Who developed Python Programming Language?", answers: ["Wick van Rossum", "Guido van Rossum", "Rasmus Lerdorf", "All of the mentioned"], correct: 2},
{level:"3", theme: "Python", question: "All keywords in Python are in _________", answers: ["Capitalized", "LOWER CASE", "UPPER CASE", "None of the mentioned."], correct: 3},
{level:"3", theme: "Python", question: "Is Python case sensitive when dealing with identifiers?", answers: ["yes", "no", "machine dependent", "none of the mentioned"], correct: 2},
{level:"3", theme: "Python", question: "EXTENSION OF PYTHON", answers: [".python", ".pl", ".py", ".p"], correct: 3},
{level:"3", theme: "Python", question: "Is Python code compiled or interpreted?", answers: ["Python code is both compiled and interpreted", " Python code is neither compiled nor interpreted", "Python code is only compiled", " Python code is only interpreted"], correct: 1},
{level:"3", theme: "Python", question: "What will be the value of the following Python expression? 4 + 3 % 5", answers: ["7", "8", "2", "1"], correct: 1},
{level:"3", theme: "Python", question: "Which of the following is used to define a block of code in Python language?", answers: [" Indentation.", "Key", "Brackets", "All of the mentioned"], correct: 1},
{level:"3", theme: "Python", question: "Which keyword is used for function in Python language?", answers: ["Function", "Def", "Fun", "Define"], correct: 2},
{level:"3", theme: "Python", question: "Which of the following functions can help us to find the version of python that we are currently working on?", answers: ["sys.version(1)", "sys.version(0)", "sys.version", " sys.version()"], correct: 1},
{level:"3", theme: "Python", question: "Which of the following character is used to give single-line comments in Python", answers: ["#.", "//", "/*", "!"], correct: 1},
{level:"3", theme: "Python", question: "Python supports the creation of anonymous functions at runtime, using a construct called __________", answers: ["lambda", "anonymous", "pi", "none of the mentioned"], correct: 1},
{level:"3", theme: "Python", question: "What will be the output of the following Python code snippet if x=1?x<<2", answers: ["4", "2", "8", "1"], correct: 2},
{level:"3", theme: "Python", question: "Which of the following is not a core data type in Python programming", answers: ["Tuples", "Lists", "Class", "Dictionary"], correct: 3},
{level:"3", theme: "Python", question: "Which one of the following is not a keyword in Python language?", answers: ["assert", "pass", "eval", "nonlocal"], correct: 3},
{level:"3", theme: "Python", question: "Which of the following is a Python tuple?", answers: ["{}", " {1, 2, 3}", "(1, 2, 3)", "[1, 2, 3]"], correct: 3},
{level:"3", theme: "Python", question: "What arithmetic operators cannot be used with strings in Python?", answers: ["+", "*", "-", "/"], correct: 3},
{level:"3", theme: "Python", question: "Which of the following functions is a built-in function in python", answers: ["print()", "factorial()", "factorial()", "sqrt()"], correct: 1},
{level:"3", theme: "Python", question: " Which of the following is the truncation division operator in Python?", answers: ["//", "\\", "|", "/"], correct: 1},
{level:"3", theme: "Python", question: "min(max(False,-3,-4), 2,7)", answers: ["false", "4", "5", "-6"], correct: 1},
{level:"3", theme: "Python", question: "What will be the output of the following Python code? \"print(\"abc. DEF\".capitalize())\"", answers: ["Abc. def", "abc.def", "Abc.Def", "ABC.DEF"], correct: 1},
/****************************************** 		level 4 ----------- Python 		******************************************/
{level:"4", theme: "Python", question: "What arithmetic operators cannot be used with strings in Python?", answers: ["+", "*", "-", "/"], correct: 3},
{level:"4", theme: "Python", question: "Which of the following functions is a built-in function in python", answers: ["print()", "factorial()", "println()", "sum()"], correct: 1},
{level:"4", theme: "Python", question: " Which of the following is the truncation division operator in Python?", answers: ["//", "\\", "|", "/"], correct: 1},
{level:"4", theme: "Python", question: "min(max(False,-3,-4), 2,7)", answers: ["false", "4", "5", "-6"], correct: 1},
/****************************************** 		level 5 ----------- Python 		******************************************/
{level:"5", theme: "Python", question: "Which of the following is not a core data type in Python programming", answers: ["Tuples", "Lists", "Class", "Dictionary"], correct: 3},
{level:"5", theme: "Python", question: "Which one of the following is not a keyword in Python language?", answers: ["assert", "pass", "eval", "nonlocal"], correct: 3},
{level:"5", theme: "Python", question: "Which of the following is a Python tuple?", answers: ["{}", "{1, 2, 3}","(1, 2, 3)","[1, 2, 3]"], correct: 3},
{level:"5", theme: "Python", question: "What will be the output of the following Python code? \"print(\"abc. DEF\".capitalize())\"", answers: ["Abc. def", "abc.def", "Abc.Def", "ABC.DEF"], correct: 1},


/****************************************** 		level 1 ----------- C++ 		******************************************/
{level:"1", theme: "C++", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "C++", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "C++", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "C++", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "C++", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "C++", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "C++", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- C++ 		******************************************/
{level:"2", theme: "C++", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "C++", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "C++", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "C++", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "C++", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "C++", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "C++", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- C++ 		******************************************/
{level:"3", theme: "C++", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "C++", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "C++", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "C++", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "C++", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "C++", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "C++", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- C++ 		******************************************/
{level:"4", theme: "C++", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "C++", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "C++", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "C++", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "C++", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "C++", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "C++", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- C++ 		******************************************/
{level:"5", theme: "C++", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "C++", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "C++", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "C++", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "C++", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "C++", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "C++", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},



/****************************************** 		level 1 ----------- HTML/CSS 		******************************************/
{level:"1", theme: "HTML", question: " HTML stands for", answers: ["HighText Machine Language", "HyperText and links Markup Language", "HyperText Markup Language", "None of these"], correct: 3},
{level:"1", theme: "HTML", question: "HighText Machine Language", answers: ["<A>", "<P>", "<b>", "<br>"], correct: 3},
{level:"1", theme: "HTML", question: " The correct sequence of HTML tags for starting a webpage is -", answers: ["HTML, Body, Title, Head", "HTML, Head, Title, Body", "HTML, Head, Title, Body", "Head, Title, HTML, body"], correct: 3},
{level:"1", theme: "HTML", question: "Which of the following tag is used for inserting the largest heading in HTML?", answers: ["<h6>", "<h3>", "<h1>", "<h2>"], correct: 3},
/****************************************** 		level 2 ----------- HTML/CSS 		******************************************/
{level:"2", theme: "HTML", question: "Which of the following tag is used to insert a line-break in HTML?", answers: ["<a>", "<b>", "<br>", "<pre>"], correct: 3},
{level:"2", theme: "HTML", question: " How to create an unordered list (a list with the list items in bullets) in HTML?", answers: ["<i>", "<li>", "<ul>", "<ol>"], correct: 3},
{level:"2", theme: "HTML", question: " Which character is used to represent the closing of a tag in HTML?", answers: ["\\", "|", "/", "."], correct: 3},
{level:"2", theme: "HTML", question: "How to create an ordered list (a list with the list items in numbers) in HTML?", answers: ["<ul>", "<ul>", "<ol>", "<i>"], correct: 3},
/****************************************** 		level 3 ----------- HTML/CSS 		******************************************/
{level:"3", theme: "HTML", question: "Which of the following element is responsible for making the text italic in HTML?", answers: ["<italic>", "<italic>", "<i>", "<pre>"], correct: 3},
{level:"3", theme: "HTML", question: " How to insert an image in HTML?", answers: ["<img href = \"jtp.png\" />", "<img url = \"jtp.png\" >", "<img src = \"jtp.png\" />", "<img link = \"jtp.png\" />"], correct: 3},
{level:"3", theme: "HTML", question: "<input> is -", answers: ["a format tag.", "None of the above", "an empty tag.", "a format tag."], correct: 3},
{level:"3", theme: "HTML", question: "How to create a checkbox in HTML?", answers: ["<input type = \"checkbox\">", "<input type = \"check\">", "<input type = \"checkbox\">", "<checkbox>"], correct: 3},
/****************************************** 		level 4 ----------- HTML/CSS 		******************************************/
{level:"4", theme: "HTML", question: "The <hr> tag in HTML is used for -", answers: ["new line", "vertical ruler", "horizontal ruler", "new paragraph"], correct: 3},
{level:"4", theme: "HTML", question: "Which of the following tag is used to add rows in the table?", answers: ["<td> and </td>", "<th> and </th>", "<tr> and </tr>", "None of the above"], correct: 3},
{level:"4", theme: "HTML", question: "Which of the following tag is used to define options in a drop-down selection list", answers: ["<select>", "<list>", "<option>", "<dropdown>"], correct: 3},
{level:"4", theme: "HTML", question: "HTML tags are enclosed in-", answers: ["# and #", "{ and }", "< and >", "! and ?"], correct: 3},
/****************************************** 		level 5 ----------- HTML/CSS 		******************************************/
{level:"5", theme: "HTML", question: " HTML stands for", answers: ["HighText Machine Language", "HyperText and links Markup Language", "HyperText Markup Language", "None of these"], correct: 3},
{level:"5", theme: "HTML", question: "HighText Machine Language", answers: ["<A>", "<P>", "<b>", "<br>"], correct: 3},
{level:"5", theme: "HTML", question: " The correct sequence of HTML tags for starting a webpage is -", answers: ["HTML, Body, Title, Head", "HTML, Head, Title, Body", "HTML, Head, Title, Body", "Head, Title, HTML, body"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following tag is used for inserting the largest heading in HTML?", answers: ["<h6>", "<h3>", "<h1>", "<h2>"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following tag is used to insert a line-break in HTML?", answers: ["<a>", "<b>", "<br>", "<pre>"], correct: 3},
{level:"5", theme: "HTML", question: " How to create an unordered list (a list with the list items in bullets) in HTML?", answers: ["<i>", "<li>", "<ul>", "<ol>"], correct: 3},
{level:"5", theme: "HTML", question: " Which character is used to represent the closing of a tag in HTML?", answers: ["\\", "|", "/", "."], correct: 3},
{level:"5", theme: "HTML", question: "How to create an ordered list (a list with the list items in numbers) in HTML?", answers: ["<ul>", "<ul>", "<ol>", "<i>"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following element is responsible for making the text italic in HTML?", answers: ["<italic>", "<italic>", "<i>", "<pre>"], correct: 3},
{level:"5", theme: "HTML", question: " How to insert an image in HTML?", answers: ["<img href = \"jtp.png\" />", "<img url = \"jtp.png\" >", "<img src = \"jtp.png\" />", "<img link = \"jtp.png\" />"], correct: 3},
{level:"5", theme: "HTML", question: "<input> is -", answers: ["a format tag.", "None of the above", "an empty tag.", "a format tag."], correct: 3},
{level:"5", theme: "HTML", question: "How to create a checkbox in HTML?", answers: ["<input type = \"checkbox\">", "<input type = \"check\">", "<input type = \"checkbox\">", "<checkbox>"], correct: 3},
{level:"5", theme: "HTML", question: "The <hr> tag in HTML is used for -", answers: ["new line", "vertical ruler", "horizontal ruler", "new paragraph"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following tag is used to add rows in the table?", answers: ["<td> and </td>", "<th> and </th>", "<tr> and </tr>", "None of the above"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following tag is used to define options in a drop-down selection list", answers: ["<select>", "<list>", "<option>", "<dropdown>"], correct: 3},
{level:"5", theme: "HTML", question: "HTML tags are enclosed in-", answers: ["# and #", "{ and }", "< and >", "! and ?"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following tag is used to create a combo box (or drop-down box)?", answers: ["<list>", "<ul>", "<select>", "<input type = \"dropdown\">"], correct: 3},
{level:"5", theme: "HTML", question: "In HTML5, which of the following tag is used to initialize the document type?", answers: ["<Doctype HTML>", "<\Doctype html>", "<!DOCTYPE html>", "<Doctype>"], correct: 3},
{level:"5", theme: "HTML", question: "What are the types of unordered or bulleted list in HTML?", answers: ["polygon, triangle, circle", "disc, square, triangle", "disc, circle, square", "All of the above"], correct: 3},
{level:"5", theme: "HTML", question: "Which of the following is the container for <tr>, <th>, and <td> ?", answers: ["<data>", "<group>", "<table>", "All of the above"], correct: 3},

];